version: '2'
services:
    db:
        image: postgres
    web:
        restart: always
        build: .
        command: bash start.sh
        volumes:
            - .:/hackertest
        ports:
            - "8000:8000"
        depends_on:
            - db
